let CODES=[];
const $=s=>document.querySelector(s);
async function loadCodes(){const r=await fetch('data/codes.json?v='+Date.now());if(!r.ok)throw new Error('Não foi possível carregar o catálogo.');CODES=await r.json();return CODES}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function shortUrl(c){return `go/${encodeURIComponent(c.id)}/`}
function itemUrl(c){return `codigo/${encodeURIComponent(c.slug||c.id)}/`}
function card(c){return `<article class="card"><img class="cover" src="${esc(c.image||'assets/default.svg')}" alt="${esc(c.title)}" loading="lazy"><div class="cardbody"><div class="eyebrow">${esc(c.category||'IA')} · #${esc(c.id)}</div><h3>${esc(c.title)}</h3><p>${esc(c.description||'')}</p><div class="tags">${(c.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="actions"><a class="btn secondary" href="${itemUrl(c)}">Detalhes</a><a class="btn" href="${shortUrl(c)}">Abrir</a></div></div></article>`}
function render(list,host){if(!host)return;host.innerHTML=list.length?list.map(card).join(''):`<div class="empty">Nenhum conteúdo encontrado.</div>`}
async function initHome(){try{await loadCodes();const visible=CODES.filter(x=>x.status!=='archived'&&x.status!=='draft');const featured=visible.filter(x=>x.featured);render(featured.length?featured:visible.slice(0,6),$('#featured'));render(visible.slice().reverse().slice(0,6),$('#latest'));if($('#count'))$('#count').textContent=visible.length}catch(e){if($('#featured'))$('#featured').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function initCatalog(){try{await loadCodes();const visible=CODES.filter(x=>x.status!=='archived'&&x.status!=='draft');const q=$('#q'),cat=$('#cat'),host=$('#catalog');const cats=[...new Set(visible.map(x=>x.category).filter(Boolean))].sort();cat.innerHTML='<option value="">Todas as categorias</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');function apply(){const term=q.value.toLowerCase().trim(),cv=cat.value;render(visible.filter(x=>(!cv||x.category===cv)&&(!term||[x.title,x.description,x.category,...(x.tags||[])].join(' ').toLowerCase().includes(term))),host)}q.oninput=apply;cat.onchange=apply;apply()}catch(e){$('#catalog').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function initItem(){try{await loadCodes();const path=location.pathname.split('/').filter(Boolean);const slug=path[path.indexOf('codigo')+1]||new URLSearchParams(location.search).get('id');const c=CODES.find(x=>(x.slug||x.id)===slug||x.id===slug);if(!c){document.body.innerHTML='<main class="container" style="padding:80px"><h1>Conteúdo não encontrado</h1></main>';return}document.title=c.title+' — CódigoIA';const item=$('#item');item.innerHTML=`<div class="detailgrid"><div><img class="cover" src="${esc(c.image||'assets/default.svg')}" alt="${esc(c.title)}"></div><div><div class="eyebrow">${esc(c.category||'IA')} · #${esc(c.id)}</div><h1>${esc(c.title)}</h1><p>${esc(c.description||'')}</p><div class="tags">${(c.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="tools"><a class="btn" href="${shortUrl(c)}">Abrir recurso</a><button class="btn secondary" id="copy">Copiar link</button></div></div></div><section class="contentbox"><h2>Sobre este conteúdo</h2><p>Recurso publicado pelo CódigoIA. Copie, cole e use.</p></section>`;$('#copy').onclick=async()=>{await navigator.clipboard.writeText(location.href);$('#copy').textContent='Copiado ✓'}}catch(e){document.body.innerHTML=`<main class="container" style="padding:80px"><h1>Erro</h1><p>${esc(e.message)}</p></main>`}}
async function initGo(){await loadCodes();const id=new URLSearchParams(location.search).get('c');const c=CODES.find(x=>x.id===id);if(c?.url)location.replace(c.url);else document.body.innerHTML='<main class="container" style="padding:80px"><h1>Link não encontrado</h1><p>Confira o código.</p></main>'}
