let CODES=[];const $=(s,r=document)=>r.querySelector(s);
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function validUrl(v=""){try{const u=new URL(String(v).trim());return u.protocol==='http:'||u.protocol==='https:'}catch{return false}}
function urlOf(x){return validUrl(x?.url)?x.url.trim():''}
function itemUrl(x){return `item.html?id=${encodeURIComponent(x.id)}`}
function imgOf(x){return x?.image||'assets/default.svg'}
function norm(v=""){return String(v).toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/^#/,'').trim()}
function matches(x,q){q=norm(q);if(!q)return true;const id=norm(x.id),n=String(parseInt(x.id,10));const text=norm([x.id,x.title,x.slug,x.category,x.description,...(x.tags||[])].join(' '));return id===q||n===q||id.padStart(3,'0')===q.padStart(3,'0')||text.includes(q)}
function visible(){return CODES.filter(x=>x.status!=='archived'&&x.status!=='draft')}
async function loadCodes(){const r=await fetch(`data/codes.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('Não foi possível carregar os códigos.');CODES=await r.json();return CODES}
function fallback(){return "this.onerror=null;this.src='assets/default.svg';"}
function badge(x){return `<span class="code-badge">#${esc(String(x.id).padStart(3,'0'))}</span>`}
function openBtn(x,label='Abrir →'){const u=urlOf(x);return u?`<a class="action-btn primary" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${label}</a>`:`<button class="action-btn disabled" disabled>URL inválida</button>`}
function card(x){return `<article class="content-card"><a class="card-image-wrap" href="${itemUrl(x)}"><img class="card-image" src="${esc(imgOf(x))}" alt="${esc(x.title||'Código')}" loading="lazy" onerror="${fallback()}">${badge(x)}</a><div class="card-body"><div class="card-category">${esc(x.category||'CÓDIGO')}</div><h3>${esc(x.title||'Sem título')}</h3><p>${esc(x.description||'Conteúdo pronto para usar.')}</p><div class="card-actions"><a class="action-btn secondary" href="${itemUrl(x)}">Detalhes</a>${openBtn(x)}</div></div></article>`}
function icon(c=''){const v=norm(c);if(v.includes('imagem'))return '▧';if(v.includes('video'))return '▶';if(v.includes('automacao'))return '⚙';if(v.includes('pesquisa'))return '⌕';if(v.includes('ia'))return '✦';return '</>'}
function quick(x){return `<a class="quick-item" href="${itemUrl(x)}"><span class="quick-icon">${icon(x.category)}</span><span class="quick-text"><strong>#${esc(String(x.id).padStart(3,'0'))}</strong><span>${esc(x.title||'Sem título')}</span><small>${esc(x.category||'Código')}</small></span><span class="quick-arrow">→</span></a>`}
function render(xs,h){if(!h)return;h.innerHTML=xs.length?xs.map(card).join(''):`<div class="empty-state"><strong>Nenhum código encontrado.</strong><span>Tente outro nome ou código, como #005.</span></div>`}
function homeSearch(){const f=$('#homeSearch'),i=$('#homeSearchInput');if(!f||!i)return;const go=q=>location.href=`catalog.html${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`;f.addEventListener('submit',e=>{e.preventDefault();go(i.value)});document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>go(b.dataset.search))}
async function initHome(){try{await loadCodes();const xs=visible(),quickXs=xs.slice().sort((a,b)=>parseInt(a.id)-parseInt(b.id)).slice(0,6),feat=xs.filter(x=>x.featured);$('#quickCodes').innerHTML=quickXs.length?quickXs.map(quick).join(''):`<div class="empty-state">Nenhum código publicado ainda.</div>`;render((feat.length?feat:xs.slice().reverse()).slice(0,3),$('#featured'));homeSearch()}catch(e){const m=esc(e.message);if($('#quickCodes'))$('#quickCodes').innerHTML=`<div class="empty-state">${m}</div>`;if($('#featured'))$('#featured').innerHTML=`<div class="empty-state">${m}</div>`}}
async function initCatalog(){try{await loadCodes();const xs=visible(),q=$('#q'),cat=$('#cat'),host=$('#catalog'),count=$('#resultCount');const cats=[...new Set(xs.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));cat.innerHTML='<option value="">Todas as categorias</option>'+cats.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');const p=new URLSearchParams(location.search);q.value=p.get('q')||'';function apply(){const term=q.value.trim(),c=cat.value,filtered=xs.filter(x=>(!c||x.category===c)&&matches(x,term));render(filtered,host);count.textContent=filtered.length;$('#catalogTitle').textContent=term?`Resultados para “${term}”`:c?c:'Todos os códigos'}q.oninput=apply;cat.onchange=apply;$('#clearFilters').onclick=()=>{q.value='';cat.value='';history.replaceState(null,'','catalog.html');apply();q.focus()};apply()}catch(e){$('#catalog').innerHTML=`<div class="empty-state"><strong>Erro</strong><span>${esc(e.message)}</span></div>`}}
async function initItem(){try{await loadCodes();const p=new URLSearchParams(location.search),id=p.get('id'),slug=p.get('slug'),path=location.pathname.split('/').filter(Boolean),ci=path.indexOf('codigo'),ps=ci>=0?path[ci+1]:'';const x=CODES.find(y=>(id&&String(y.id)===String(id))||(slug&&y.slug===slug)||(ps&&(y.slug===ps||String(y.id)===ps)));if(!x){$('#item').innerHTML='<div class="not-found"><span class="eyebrow">CÓDIGOIA</span><h1>Conteúdo não encontrado</h1><p>Confira o código informado ou volte para a biblioteca.</p><a class="action-btn primary big-btn" href="catalog.html">Voltar aos códigos</a></div>';return}document.title=`${x.title||'Conteúdo'} — CódigoIA`;const u=urlOf(x),tags=(x.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');$('#item').innerHTML=`<a class="back-link" href="catalog.html">← Voltar para códigos</a><div class="detail-shell"><div class="detail-media"><div class="detail-image-frame"><img src="${esc(imgOf(x))}" alt="${esc(x.title||'Código')}" onerror="${fallback()}">${badge(x)}</div></div><div class="detail-info"><div class="detail-category"><span>${esc(x.category||'CÓDIGO')}</span><b>#${esc(String(x.id).padStart(3,'0'))}</b></div><h1>${esc(x.title||'Sem título')}</h1><p class="detail-description">${esc(x.description||'Conteúdo pronto para usar.')}</p>${tags?`<div class="tags">${tags}</div>`:''}<div class="code-callout"><div><span>USE ESTE CÓDIGO NO SITE</span><strong>#${esc(String(x.id).padStart(3,'0'))}</strong></div><button class="copy-code" id="copyCode">Copiar código</button></div><div class="detail-actions">${u?`<a class="action-btn primary big-btn" href="${esc(u)}" target="_blank" rel="noopener noreferrer">Abrir recurso <span>↗</span></a>`:'<button class="action-btn disabled big-btn" disabled>URL inválida</button>'}<button class="action-btn secondary big-btn" id="copyLink">Copiar link</button></div></div></div><section class="about-box"><span class="eyebrow">SOBRE</span><h2>${esc(x.title||'Este conteúdo')}</h2><p>Encontre este conteúdo rapidamente pesquisando pelo código <strong>#${esc(String(x.id).padStart(3,'0'))}</strong> no CódigoIA.</p></section>`;$('#copyCode').onclick=()=>copyText(`#${String(x.id).padStart(3,'0')}`,$('#copyCode'),'Copiado ✓');$('#copyLink').onclick=()=>copyText(location.href,$('#copyLink'),'Link copiado ✓')}catch(e){$('#item').innerHTML=`<div class="not-found"><span class="eyebrow">ERRO</span><h1>Não foi possível carregar</h1><p>${esc(e.message||'Erro desconhecido.')}</p><a class="action-btn primary big-btn" href="catalog.html">Voltar</a></div>`}}
async function copyText(t,b,s){try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}const old=b.textContent;b.textContent=s;setTimeout(()=>b.textContent=old,1800)}
document.addEventListener('DOMContentLoaded',()=>{const p=document.body.dataset.page;if(p==='home')initHome();if(p==='catalog')initCatalog();if(p==='item')initItem()});
